# Generated by Django 5.1.5 on 2025-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('metier', models.CharField(choices=[('APD', 'APD'), ('DFE', 'DFE'), ('FCA', 'FCA')], max_length=20)),
                ('est_inscrit', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
