# Generated by Django 5.1.5 on 2025-03-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
