# Generated by Django 5.1.5 on 2025-03-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_alter_etudiant_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
